algoritmo "semnome"
// Função :
// Autor :
// Data : 16/05/2017
// Seção de Declarações 
var
n: inteiro

inicio
// Seção de Comandos 
escreva("Digite um numero: ")
leia(n)
escolha(n)
  caso 1
   escreva("Um")
  caso 2
     escreva("Dois")
  caso 3
     escreva("Três")
  caso 4
     escreva("Quatro")
  caso 5
     escreva("Cinco")
  outrocaso
   escreva("Numero inválido.")
fimescolha


fimalgoritmo
